version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis

  clients:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - app