definitions:
  github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.FreePost:
    properties:
      UUID:
        type: string
    required:
    - UUID
    type: object
  github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.RentPost:
    properties:
      UUID:
        type: string
      city:
        type: string
      latitude:
        type: number
      longitude:
        type: number
    required:
    - UUID
    - city
    - latitude
    - longitude
    type: object
  github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.ScooterGet:
    properties:
      UUID:
        type: string
      availability:
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
    type: object
  model.ApiError:
    properties:
      Message:
        type: string
    type: object
info:
  contact: {}
paths:
  /free:
    post:
      parameters:
      - default: 00000000-0000-0000-0000-000000000000
        description: ClientID
        in: header
        maxLength: 36
        minLength: 36
        name: client_id
        required: true
        type: string
      - description: Scooter to free information
        in: body
        name: Payload
        required: true
        schema:
          $ref: '#/definitions/github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.FreePost'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ApiError'
      summary: Free the given scooter.
      tags:
      - scooters
  /rent:
    post:
      parameters:
      - default: 00000000-0000-0000-0000-000000000000
        description: ClientID
        in: header
        maxLength: 36
        minLength: 36
        name: client_id
        required: true
        type: string
      - description: Rental information details
        in: body
        name: Payload
        required: true
        schema:
          $ref: '#/definitions/github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.RentPost'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ApiError'
      summary: Rents the chosen scooter in given city.
      tags:
      - scooters
  /scooters:
    get:
      parameters:
      - default: 00000000-0000-0000-0000-000000000000
        description: ClientID
        in: header
        maxLength: 36
        minLength: 36
        name: client_id
        required: true
        type: string
      - default: Ottawa
        description: City
        in: query
        name: city
        required: true
        type: string
      - default: 73.4
        description: Longitude of the center of the rectangle
        in: query
        name: longitude
        required: true
        type: number
      - default: 45.4
        description: Latitude of the center of the rectangle
        in: query
        name: latitude
        required: true
        type: number
      - default: 20000
        description: Height of the rectangle in meters
        in: query
        name: height
        required: true
        type: number
      - default: 25000
        description: Width of the rectangle in meters
        in: query
        name: width
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_NordSecurity-Interviews_BE-PatrykPasterny_internal_model.ScooterGet'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ApiError'
      summary: Gets scooters in the queried area of given city.
      tags:
      - scooters
swagger: "2.0"
